[package]
name = "dnstt-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
nix = { version = "0.29.0", features = ["signal"] }
rand = "0.8.5"
tokio = { version = "1.40.0", features = ["full"] }
