[package]
name = "dnstt-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
rand = "0.8.5"
tokio = { version = "1.40.0", features = ["full"] }
log = "0.4"
env_logger = "0.11.5"
