[package]
name = "tunnel-tool-tester"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
rand = "0.8.5"
tokio = { version = "1.40.0", features = ["full"] }
